#! /usr/bin/env php
<?php

switch ($argv[1]) {
	case 'songstart':
		$f = fopen( 'php://stdin', 'r' );
		while($line = fgets($f)) {
			list($key, $value) = explode('=', $line);
			if (in_array($key, array('title', 'artist'))) {
				$$key = trim($value);
			} // end if (in_array($key, array('title', 'artist')))
		}
		fclose($f);
		file_put_contents('/tmp/pianobar', sprintf('"%s" by %s', $title, $artist));
		break;
} // end switch ($argv[1])
