#!/usr/bin/env node
const { spawnSync } = require("child_process");

const [
  _CMD,
  _SCRIPT,
  API_VERSION,
  ARGS,
  COMMAND,
  RC_FILE,
  DATA_DIR,
  VERSION,
  INPUT,
  OUTPUT
] = process.argv;
const command = COMMAND.split(":")[1];

const changeCommands = [
  "add",
  "append",
  "annotate",
  "delete",
  "denotate",
  "done",
  "duplicate",
  "import",
  "modify",
  "prepend",
  "purge",
  "start",
  "stop",
  "synchronize",
  "undo"
];

if (!changeCommands.includes(command)) {
  process.exit(0);
}

const exec = (cmd, ...args) => {
  const options = {
    shell: true,
    cwd: DATA_DIR.split(":")[1]
  };
  const { error, stderr, stdout } = spawnSync(cmd, args, options);
  if (error) {
    console.log(`${command} failed in on-exit hook.  
args   : ${args.join(" ")}
error  : ${error}
output : ${stdout}
stderr : ${stderr}`);
    process.exit(1);
    return "";
  }
  return stdout.toString();
};
const git = exec("which", "git").trim();
const commit = exec(`${git} commit -am "Updated Tasks"`);
const push = exec(`${git} push origin master`);
console.log("synced to git");
